version: "3.5"

services:
  roaddefectsservice.presentation.web:
    image: ${DOCKER_REGISTRY-}roaddefectsservicepresentationweb
    build:
      context: .
      dockerfile: RoadDefectsService.Presentation.Web/Dockerfile
    ports:
      - "80:8080"
    networks:
      - my-net
    depends_on:
      - redis
      - postgres
      
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: RoadDefectsStore
    expose:
      - "5432:5432"
    networks:
      - my-net
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my-net
      
networks:
  my-net:
    driver: bridge


# version: '3.4'

# services:
  # roaddefectsservice.presentation.web:
  #   image: ${DOCKER_REGISTRY-}roaddefectsservicepresentationweb
  #   build:
  #     context: .
  #     dockerfile: RoadDefectsService.Presentation.Web/Dockerfile
