version: "3.5"

services:
  app:
    container_name: dotnetbackend
    build:
      context: .
      dockerfile: RoadDefectsService.Presentation.Web/Dockerfile
    ports:
      - "80:8080"
    networks:
      - my-net
    depends_on:
      - db
      
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: RoadDefectsService
    expose:
      - "5432"
    networks:
      - my-net

networks:
  my-net:
    driver: bridge